---
abstract: 'tie a variable to a type constraint'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Fatal: 0
  Test::Requires: 0
  Types::Standard: 0.004
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.009, CPAN::Meta::Converter version 2.120921'
keywords: []
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Type-Tie
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
provides:
  Type::Tie:
    file: lib/Type/Tie.pm
    version: 0.004
  Type::Tie::ARRAY:
    file: lib/Type/Tie.pm
    version: 0.004
  Type::Tie::BASE:
    file: lib/Type/Tie.pm
    version: 0.004
  Type::Tie::HASH:
    file: lib/Type/Tie.pm
    version: 0.004
  Type::Tie::SCALAR:
    file: lib/Type/Tie.pm
    version: 0.004
requires:
  Exporter::TypeTiny: 0.004
  Hash::FieldHash: 0
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Type-Tie/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Type-Tie
  homepage: https://metacpan.org/release/Type-Tie
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-type-tie
version: 0.004
